# Generated by Django 4.2.9 on 2024-03-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='task_commen_time_cr_169e99_idx',
            old_name='app_comment_time_cr_0c0ec5_idx',
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
