# Generated by Django 4.2.9 on 2024-03-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_app_comment_time_cr_0c0ec5_idx_task_commen_time_cr_169e99_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='app_comment_time_cr_0c0ec5_idx',
            old_name='task_commen_time_cr_169e99_idx',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='app_comments',
        ),
    ]
